### PR TITLE
Update variables.tf

### PR DESCRIPTION
**Pull request by zixo**
## what

Specified value type of variable api_integration

## why

Terraform treated the value like a string

### CODE REVIEW

**Comment by gberenice** [comment]
@zixo thanks! Could you please also update the variable in the child module: https://github.com/cloudposse/terraform-opsgenie-incident-management/blob/main/modules/api_integration/variables.tf#L1 ?

**Comment by matusso** [comment]
> @zixo thanks! Could you please also update the variable in the child module: https://github.com/cloudposse/terraform-opsgenie-incident-management/blob/main/modules/api_integration/variables.tf#L1 ?

I would say he did it exactly there :)

**Comment by gberenice** [comment]
> @gberenice I would say he did it exactly there :)

@matusso, pardon, my bad. I wanted to say that root and child modules should use the same variable definitions for consistency. 
The type for the variable `api_integration` was updated in one place, and it would be great to address this change in the root module https://github.com/cloudposse/terraform-opsgenie-incident-management/blob/main/variables.tf#L12-L15.
Does that make sense?

**Comment by zixo** [comment]
Thank you @matusso @gberenice

**Comment by gberenice** [comment]
@zixo Ah, one more thing - README.md is outdated now. 
Please run the following commands locally and push the file:
```
  make init
  make readme
```

**Review by gberenice — APPROVED** [review]
LGTM 👍 
Thanks @zixo

**Comment by gberenice** [comment]
@osterman @aknysh @Nuru a release is having problems, probably because of the existing draft. Please take a look ([release log](https://github.com/cloudposse/terraform-opsgenie-incident-management/actions/runs/8295665498/job/22703184706)):
```
Error: Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}
```

**Pull request merged**
