### PR TITLE
[Notification Policy] Improve module

### PR DESCRIPTION
**Pull request by diraol**
## what

Added many missing structures, which also required a bit of "refactoring".

## references

- https://registry.terraform.io/providers/opsgenie/opsgenie/latest/docs/resources/notification_policy#de_duplication_action
- https://registry.terraform.io/providers/opsgenie/opsgenie/latest/docs/resources/notification_policy#delay_action

### CODE REVIEW

**Comment by diraol** [comment]
@goruha sorry for the direct poke, but we are indeed in need of this feature for a project :)

**Comment by diraol** [comment]
Hey folks, if you are still open for new contributions I have some other improvements I have more to add (it is in my fork, and I'd be happy to send it back here).

**Comment by hans-d** [comment]
@diraol certainly open for new contributions. Currently cleaning up a lot of outdated code, so that visibility on new stuff gets improved.
If you can fix this one (the re`dme check will tell you whats missing), would love to see additional contributions in separate prs (easier to review and process).

**Comment by diraol** [comment]
Hey @hans-d sorry for the long time to make it.
I've split the changes into multiple PRs and updated this one too :)
Let's see how it goes.

**Review by Benbentwo — APPROVED** [review]

**Pull request merged**
