### PR TITLE
[Existing Resources] Add Team and Schedule

### PR DESCRIPTION
**Pull request by diraol**
## what

Add the ability to "import" (data) existing scheduling and team.

## why

This is utterly useful especially for migrations with resources managed manually or to integrate multiple teams that handle opsgenie differently (some automated, some manually).

### CODE REVIEW

**Comment by diraol** [comment]
This one should be "fixed" as soon as the other PRs are merged.

**Review by Benbentwo — APPROVED** [review]
/terratest

**Review by Benbentwo — CHANGES_REQUESTED** [review]
With the data source looked up we need a resource to import it to.

if these are for imports then these should be resources. they can include the `import` block.

though is there a reason the code in `main` branch cannot be used with a `terraform import` for the opsgenie schedule?

**Comment by diraol** [comment]
> With the data source looked up we need a resource to import it to.
> 
> if these are for imports then these should be resources. they can include the `import` block.
> 
> though is there a reason the code in `main` branch cannot be used with a `terraform import` for the opsgenie schedule?

Over here we are using a CI to run all opentofu procedures (plan/apply). Users do not have permission to run it locally, so `import` is not an options (building a pipeline to handle a 1 time import seems much more complex).

I just don't get why:

> With the data source looked up we need a resource to import it to.

**Comment by Benbentwo** [comment]
If we add the datasource for the `opsgenie_schedule` and `opsgenie_team` and then you run terraform import for them something like `terraform import opsgenie_schedule.test <my schedule id>`. 2 things will happen:
1. Import will fail because you can only import into a **resource** not a **datasource**
2. If you could import into a datasource, they are currently unused and would not affect anything.

The reason the `existing_users.tf` was there was because if there were already users, we look them up (not stored in state yet) and then use them instead for various resources. Essentially allowing other resources to be created and stored in state by directly creating a user, or looking them up.


Regarding your problem:
> Over here we are using a CI to run all opentofu procedures (plan/apply). Users do not have permission to run it locally, so import is not an options (building a pipeline to handle a 1 time import seems much more complex).

I think you have 2 options.
1. you need to `terraform import` with someone who has access to run locally - this is the cleanest way
2. Destroy the resources by hand and recreate them using terraform - this is less ideal as you might lose configuration / have some down time.

**Comment by Benbentwo** [comment]
The other option - is if we want to support lookups of teams and schedules, then `existing_schedules     = lookup(var.opsgenie_resources, "existing_schedules", [])` should be pointing to the datasources and we also need to use that variable (`existing_schedules`)

**Comment by diraol** [comment]
Conflicts fixed and I've also added some changes that were missing (again, forgot while splitting the PR) related to data objects.

See if it make sense @Benbentwo - If it doesn't, no hard feelings! :)

**Review by Benbentwo — APPROVED** [review]
This looks fine, tests are failing from conflicts (which isn't caused by this PR), config module is unfortunately one that we have tests disabled. we can roll this back if there's any issues or roll forward

**Pull request merged**
